import type { AppSnapshot } from '../../domain/entities/AppSnapshot';

const createdAt = '2026-01-01T00:00:00.000Z';

export function createInitialSnapshot(): AppSnapshot {
  return {
    version: 3,
    accounts: [
      {
        id: 'account-main',
        name: 'Conta principal',
        type: 'checking',
        initialBalanceInCents: 0,
        initialBalanceDate: '2026-01-01',
        isDefault: true,
        isActive: true,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: 'account-cash',
        name: 'Dinheiro',
        type: 'cash',
        initialBalanceInCents: 0,
        initialBalanceDate: '2026-01-01',
        isDefault: true,
        isActive: true,
        createdAt,
        updatedAt: createdAt,
      },
    ],
    categories: [
      {
        id: 'category-food',
        name: 'Alimentação',
        type: 'expense',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-home',
        name: 'Moradia',
        type: 'expense',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-transport',
        name: 'Transporte',
        type: 'expense',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-health',
        name: 'Saúde',
        type: 'expense',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-education',
        name: 'Educação',
        type: 'expense',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-leisure',
        name: 'Lazer',
        type: 'expense',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-subscriptions',
        name: 'Assinaturas',
        type: 'expense',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-shopping',
        name: 'Compras',
        type: 'expense',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-salary',
        name: 'Salário',
        type: 'income',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-extra-income',
        name: 'Renda extra',
        type: 'income',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-refund',
        name: 'Reembolso',
        type: 'income',
        isDefault: true,
        isActive: true,
        createdAt,
      },
      {
        id: 'category-other',
        name: 'Outros',
        type: 'both',
        isDefault: true,
        isActive: true,
        createdAt,
      },
    ],
    transactions: [],
    settings: {
      theme: 'light',
      locale: 'pt-BR',
      currency: 'BRL',
      financialMonthStartDay: 1,
      notificationsEnabled: false,
      notificationDaysBefore: 1,
      notificationHour: 9,
      appLockMode: 'none',
    },
  };
}
